Use GtkFileChooserNative
virt-manager/virt-manager pull request #636
Opened 2024-03-20 06:46 UTC by michaelweghorn

Use [GtkFileChooserNative](https://docs.gtk.org/gtk3/class.FileChooserNative.html) instead of [GtkFileChooserDialog](https://docs.gtk.org/gtk3/class.FileChooserDialog.html) to integrate better with the platform (e.g. use the portal implementation when run with GTK_USE_PORTAL=1, resulting in the KDE Frameworks implementation being used when
xdg-desktop-portal-kde is in use). Quoting from the [GtkFileChooserDialog doc](https://docs.gtk.org/gtk3/class.FileChooserDialog.html):

> If you want to integrate well with the platform you should use the
> GtkFileChooserNative API, which will use a platform-specific dialog if
> available and fall back to GtkFileChooserDialog otherwise.

Also replace the use of [GTK_STOCK_CANCEL](https://docs.gtk.org/gtk3/const.STOCK_CANCEL.html) and [GTK_STOCK_OPEN](https://docs.gtk.org/gtk3/const.STOCK_OPEN.html) which were deprecated in GTK 3.10 with the corresponding labels as suggested in their doc.

2024-03-20 07:33 UTC, ptoscano requested changes
Thanks for the patch, which seems a good improvement. Since this seems to fix #315, please amend the commit message adding eg
```
Fixes #315
```
at the bottom of it.

Regarding the change on `choose_button`: this does not seem correct, as `Gtk.STOCK_*` are icon names, and it is actually used as such:
https://github.com/virt-manager/virt-manager/blob/dadb9a0d6fbfc4b1f106e59bd3b0ff06a5bf253a/virtManager/vmwindow.py#L557-L564

maybe what could be done here as part of this work is to change the `choose_button` parameter into `choose_label`, and change the only usage to pass `_("_Save")` instead of the icon name. Also, it seems that Gtk.FileChooserDialog has defaults for `accept_label` and `cancel_label`, so I'd always pass `None` for `cancel_label`, and use `None` as default for `accept_label`.

[1] https://docs.gtk.org/gtk3/class.FileChooserNative.html#properties

2024-03-20 08:43 UTC, michaelweghorn commented
> Thanks for the patch, which seems a good improvement. Since this seems to fix #315, please amend the commit message adding eg
> 
> ```
> Fixes #315
> ```
> 
> at the bottom of it.

Done.

> Regarding the change on `choose_button`: this does not seem correct, as `Gtk.STOCK_*` are icon names, and it is actually used as such:
> 
> https://github.com/virt-manager/virt-manager/blob/dadb9a0d6fbfc4b1f106e59bd3b0ff06a5bf253a/virtManager/vmwindow.py#L557-L564
> 
> maybe what could be done here as part of this work is to change the `choose_button` parameter into `choose_label`, and change the only usage to pass `_("_Save")` instead of the icon name. Also, it seems that Gtk.FileChooserDialog has defaults for `accept_label` and `cancel_label`, so I'd always pass `None` for `cancel_label`, and use `None` as default for `accept_label`.

Good catch! Thanks for the suggestion! That sounds good, I've implemented it this way now.

2024-03-20 08:45 UTC, michaelweghorn commented
> (...), so I'd always pass `None` for `cancel_label`, (...)

For the record, that's the default, so I just dropped that param completely.

2024-04-07 19:54 UTC, merged

2024-04-07 19:55 UTC, crobinso commented
Thanks @michaelweghorn and @ptoscano !